### ISSUE TITLE
Types query composite_type_attrs missing semicolon

### ISSUE THREAD

**Issue by TravisCardwell** [mzabani/codd#140]
I think there is a missing semicolon (concatenation) in the SQL that creates the `composite_type_attrs` attribute in the types (PostgreSQL 10) query ([code](https://github.com/mzabani/codd/blob/0b31d04ad2b0a04ef5d664bc6608b1dfdbe8f3d0/src/Codd/Representations/Database/Pg10.hs#L683-L684)), between the attribute type name and column name.

The following is the relevant code, reformatted to make the issue obvious:

```sql
pg_attribute.attname
  || ';' || attribute_type.typname
         || COALESCE(attribute_coll.collname, '')
  || ';' || COALESCE(attribute_coll_nsp.nspname, '')
```

**Comment by mzabani** [comment]
Thanks for reporting this. I merged a quick fix into `master` and have just pushed an up-to-date version of codd to the docker registry
