### ISSUE TITLE
Types query pg_class_elem not used

### ISSUE THREAD

**Issue by TravisCardwell** [mzabani/codd#143]
The `pg_class_elem` join in the (PostgreSQL 10) type query ([code](https://github.com/mzabani/codd/blob/0b31d04ad2b0a04ef5d664bc6608b1dfdbe8f3d0/src/Codd/Representations/Database/Pg10.hs#L701)) is not used.

```sql
LEFT JOIN pg_catalog.pg_class AS pg_class_elem
  ON pg_class_elem.oid = pg_type_elem.typrelid
```

**Comment by mzabani** [comment]
Nice catch, thanks!

Addressed by https://github.com/mzabani/codd/pull/144
