### ISSUE TITLE
GHC 9.4 build error (TypeOperators pragma needed)

### ISSUE THREAD

**Issue by avanov** [mzabani/codd#150]
Hi! I'm getting the following error on the latest master checkout with GHC 9.4.5 native-bignum / Apple ARM:
```
Preprocessing library for codd-0.1.1..
Building library for codd-0.1.1..
[ 1 of 28] Compiling Codd.Logging     ( src/Codd/Logging.hs, dist/build/Codd/Logging.o, dist/build/Codd/Logging.dyn_o )
[ 2 of 28] Compiling Codd.Parsing     ( src/Codd/Parsing.hs, dist/build/Codd/Parsing.o, dist/build/Codd/Parsing.dyn_o )
[ 3 of 28] Compiling Codd.Analysis    ( src/Codd/Analysis.hs, dist/build/Codd/Analysis.o, dist/build/Codd/Analysis.dyn_o )
[ 4 of 28] Compiling Codd.Prelude     ( src/Codd/Prelude.hs, dist/build/Codd/Prelude.o, dist/build/Codd/Prelude.dyn_o )
[ 5 of 28] Compiling Codd.Representations.Database.Model ( src/Codd/Representations/Database/Model.hs, dist/build/Codd/Representations/Database/Model.o, dist/build/Codd/Representations/Database/Model.dyn_o )
[ 6 of 28] Compiling Codd.Representations.Database.SqlGen ( src/Codd/Representations/Database/SqlGen.hs, dist/build/Codd/Representations/Database/SqlGen.o, dist/build/Codd/Representations/Database/SqlGen.dyn_o )
[ 7 of 28] Compiling Codd.Representations.Types ( src/Codd/Representations/Types.hs, dist/build/Codd/Representations/Types.o, dist/build/Codd/Representations/Types.dyn_o )
[ 8 of 28] Compiling Codd.Representations.Disk ( src/Codd/Representations/Disk.hs, dist/build/Codd/Representations/Disk.o, dist/build/Codd/Representations/Disk.dyn_o )
[ 9 of 28] Compiling Codd.Types       ( src/Codd/Types.hs, dist/build/Codd/Types.o, dist/build/Codd/Types.dyn_o )
[10 of 28] Compiling Codd.Representations.Database.Pg10 ( src/Codd/Representations/Database/Pg10.hs, dist/build/Codd/Representations/Database/Pg10.o, dist/build/Codd/Representations/Database/Pg10.dyn_o )
[11 of 28] Compiling Codd.Representations.Database.Pg11 ( src/Codd/Representations/Database/Pg11.hs, dist/build/Codd/Representations/Database/Pg11.o, dist/build/Codd/Representations/Database/Pg11.dyn_o )
[12 of 28] Compiling Codd.Representations.Database.Pg12 ( src/Codd/Representations/Database/Pg12.hs, dist/build/Codd/Representations/Database/Pg12.o, dist/build/Codd/Representations/Database/Pg12.dyn_o )
[13 of 28] Compiling Codd.Representations.Database.Pg13 ( src/Codd/Representations/Database/Pg13.hs, dist/build/Codd/Representations/Database/Pg13.o, dist/build/Codd/Representations/Database/Pg13.dyn_o )
[14 of 28] Compiling Codd.Representations.Database.Pg14 ( src/Codd/Representations/Database/Pg14.hs, dist/build/Codd/Representations/Database/Pg14.o, dist/build/Codd/Representations/Database/Pg14.dyn_o )
[15 of 28] Compiling Codd.Representations.Database.Pg15 ( src/Codd/Representations/Database/Pg15.hs, dist/build/Codd/Representations/Database/Pg15.o, dist/build/Codd/Representations/Database/Pg15.dyn_o )
[16 of 28] Compiling Codd.Query       ( src/Codd/Query.hs, dist/build/Codd/Query.o, dist/build/Codd/Query.dyn_o )
[17 of 28] Compiling Codd.Internal.Retry ( src/Codd/Internal/Retry.hs, dist/build/Codd/Internal/Retry.o, dist/build/Codd/Internal/Retry.dyn_o )
[18 of 28] Compiling Codd.Internal.MultiQueryStatement ( src/Codd/Internal/MultiQueryStatement.hs, dist/build/Codd/Internal/MultiQueryStatement.o, dist/build/Codd/Internal/MultiQueryStatement.dyn_o )
[19 of 28] Compiling Codd.Environment ( src/Codd/Environment.hs, dist/build/Codd/Environment.o, dist/build/Codd/Environment.dyn_o )
[20 of 28] Compiling Codd.Representations.Database ( src/Codd/Representations/Database.hs, dist/build/Codd/Representations/Database.o, dist/build/Codd/Representations/Database.dyn_o )
[21 of 28] Compiling Codd.Representations ( src/Codd/Representations.hs, dist/build/Codd/Representations.o, dist/build/Codd/Representations.dyn_o )
[22 of 28] Compiling Codd.Internal    ( src/Codd/Internal.hs, dist/build/Codd/Internal.o, dist/build/Codd/Internal.dyn_o )

src/Codd/Internal.hs:206:14: error: [-Wtype-equality-requires-operators, -Werror=type-equality-requires-operators]
    The use of ‘~’ without TypeOperators
    will become an error in a future GHC release.
    Suggested fix: Perhaps you intended to use TypeOperators
    |
206 |        , txn ~ InTxnT (ResourceT m)
    |              ^

src/Codd/Internal.hs:245:14: error: [-Wtype-equality-requires-operators, -Werror=type-equality-requires-operators]
    The use of ‘~’ without TypeOperators
    will become an error in a future GHC release.
    Suggested fix: Perhaps you intended to use TypeOperators
    |
245 |        , txn ~ InTxnT m
    |              ^

src/Codd/Internal.hs:278:42: error: [-Wtype-equality-requires-operators, -Werror=type-equality-requires-operators]
    The use of ‘~’ without TypeOperators
    will become an error in a future GHC release.
    Suggested fix: Perhaps you intended to use TypeOperators
    |
278 |      . (MonadUnliftIO m, NotInTxn m, txn ~ InTxnT m)
    |                                          ^

src/Codd/Internal.hs:510:14: error: [-Wtype-equality-requires-operators, -Werror=type-equality-requires-operators]
    The use of ‘~’ without TypeOperators
    will become an error in a future GHC release.
    Suggested fix: Perhaps you intended to use TypeOperators
    |
510 |        , txn ~ InTxnT m
    |              ^
[26 of 28] Compiling Codd.AppCommands ( src/Codd/AppCommands.hs, dist/build/Codd/AppCommands.o, dist/build/Codd/AppCommands.dyn_o )
[28 of 28] Compiling Paths_codd       ( dist/build/autogen/Paths_codd.hs, dist/build/Paths_codd.o, dist/build/Paths_codd.dyn_o )
error: builder for '/nix/store/9si3x8fc69zf1dly795yvdsj54bc17b4-codd-0.1.1.drv' failed with exit code 1;
       last 10 log lines:
       >
       > src/Codd/Internal.hs:510:14: error: [-Wtype-equality-requires-operators, -Werror=type-equality-requires-operators]
       >     The use of ‘~’ without TypeOperators
       >     will become an error in a future GHC release.
       >     Suggested fix: Perhaps you intended to use TypeOperators
       >     |
       > 510 |        , txn ~ InTxnT m
       >     |              ^
       > [26 of 28] Compiling Codd.AppCommands ( src/Codd/AppCommands.hs, dist/build/Codd/AppCommands.o, dist/build/Codd/AppCommands.dyn_o )
       > [28 of 28] Compiling Paths_codd       ( dist/build/autogen/Paths_codd.hs, dist/build/Paths_codd.o, dist/build/Paths_codd.dyn_o )
       For full logs, run 'nix log /nix/store/9si3x8fc69zf1dly795yvdsj54bc17b4-codd-0.1.1.drv'.
```

**Comment by mzabani** [comment]
Thanks a lot for this bug report!

I've created a branch and a PR to hopefully fix this. It's running tests at https://github.com/mzabani/codd/pull/151. Could you kindly check if that works for you?

In case you don't have the time, I still find it will be better to merge that and then you can try it on `master` eventually, and let me know if it works.

**Comment by avanov** [comment]
@mzabani thanks for the fix, I confirm it works.

Regarding the PR, personally I prefer `-Wall -Werror` for exactly this reason of motivating users to report compatibility issues as bugs early on the new GHC release lifecycle. The CI could setup GHC version matrix to help with testing across the board. [Here](https://github.com/avanov/typeit/blob/develop/.github/workflows/ci.yml#L8-L14) I've got an example for a Python codebase, but the matrix itself is [language-agnostic property of Github Actions](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs).

**Comment by mzabani** [comment]
Thanks for confirming.

A build matrix would be nice. It shouldn't be hard to do with the Nix flake infrastructure in place, but I wonder if I'll be abusing github's free CI too much, since CI already takes quite long.

But most of all, I wonder if it isn't better to not have `-Werror` simply because it would allow bleeding edge GHC users to compile codd instead of getting in their way, or even users of relatively new GHC still not in the build matrix. Not sure what your thoughts are about that.

I'll merge that PR for now, and this issue will be closed, but we can continue discussing if you'd like!

**Comment by avanov** [comment]
@mzabani I wouldn't worry about CI limits for open-source projects, the [current limits](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits) suggest that you may have up to 20 concurrent jobs running for 6 hours each. But the nix flakes [not being able to accept input arguments](https://discourse.nixos.org/t/passing-options-to-flakes/7579/6) is a bigger issue though, there doesn't seem to be a solution at the moment, unless the flake file is duplicated with hardcoded values and called separately via shell, so that matrix values would navigate to flake filename paths.

**Comment by avanov** [comment]
> But most of all, I wonder if it isn't better to not have -Werror simply because it would allow bleeding edge GHC users to compile codd instead of getting in their way, or even users of relatively new GHC still not in the build matrix. Not sure what your thoughts are about that.

Afaik the ghc-options could be overridden by the builder. For instance, if I have a package that specifies `-Wall -Werror` in its cabal file, and if it fails in CI because of warnings propagated into errors, I can still build it locally via `cabal v2-build --ghc-option="-Wwarn" <package-name>` if I want to test it.

I guess it's a matter of preference of which overrides have to be explicit. I prefer it when all warnings are covered either as errors or as explicitly allowed exemptions.

**Comment by mzabani** [comment]
> the [current limits](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits) suggest that you may have up to 20 concurrent jobs running for 6 hours each

Oh, that's very good to know. Codd is very distant from those limits.

> Afaik the ghc-options could be overridden by the builder. For instance, if I have a package that specifies -Wall -Werror in its cabal file, and if it fails in CI because of warnings propagated into errors, I can still build it locally via cabal v2-build --ghc-option="-Wwarn" <package-name> if I want to test it.

I think the problem is if someone just wants to put codd in their stack.yaml dependencies, or use it as a library in general. Not that that use case is recommended as of today (but we use it in the shop I work at), but in the future it probably will be.

I'm not sure how cabal handles that scenario. Does it apply the builder's GHC options to the library being built, or does it build with the library's GHC options specified in e.g. codd.cabal ?

**Comment by avanov** [comment]
> I think the problem is if someone just wants to put codd in their stack.yaml dependencies, or use it as a library in general.

Yeah, in that case you're likely to upload it to Hackage, and Hackage prohibits packages with `-Werror` in cabal files.

> Does it apply the builder's GHC options to the library being built, or does it build with the library's GHC options specified in e.g. codd.cabal ?

It does apply overrides from `calab.project`'s [`package` section](https://cabal.readthedocs.io/en/3.10/cabal-project.html#package-configuration-options) while building dependencies:

**Comment by mzabani** [comment]
> Yeah, in that case you're likely to upload it on Hackage, and Hackage prohibits packages with -Werror in cabal files.

Oh, I plan on eventually uploading codd to hackage. Even if that time is not very close, I guess this at least makes it clear that `-Werror` is best removed by default.

I still should implement a build matrix with other GHCs, particularly now that you have shown me that github CI should be able to handle it :)
