### ISSUE TITLE
Error parsing the connection string in environment variable CODD_CONNECTION: endOfInput

### ISSUE THREAD

**Issue by philwhiteuk** [mzabani/codd#195]
## Expected

`CODD_CONNECTION` string should work the same way as it would if you used it with `psql`.

## Actual

When I use a newline ending in my `CODD_CONNECTION` I get a parse error:

```
Applying SQL migrations
codd: Error parsing the connection string in environment variable CODD_CONNECTION: endOfInput
CallStack (from HasCallStack):
  error, called at src/Codd/Environment.hs:156:13 in codd-0.1.3-AYlBJZElMWeC64KQYPdpcK:Codd.Environment
```

Note: this happens whether I use the URI or key value pairs.

**Comment by mzabani** [comment]
Thanks a lot for your report, @philwhiteuk !

I tested locally with psql and I can confirm psql allows whitespace not just at the end, but around the `=` sign and kvps when using the kvp format for connection strings (and the docs [even say so](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING)):

```
psql 'dbname
>
> =
>    codd-experiments'
psql (16.1)
Type "help" for help.

codd-experiments=>
\q
```

But the URI format doesn't accept newlines even at the end:

```
 $ psql 'postgres://codd_admin@localhost/codd-experiments
>
>
>
> '
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "codd-experiments



" does not exist
```

Can you confirm if the URI format with newlines at the end (or in other positions) works for you with psql?

**Comment by mzabani** [comment]
@philwhiteuk I merged a PR that allows white-space separating kvps but the parsing of URI connection strings remains the same. I did that because this was indeed a bug (and thank you very much for your report!) and because it seems codd is doing the right thing for URI connection strings, but please feel free to reopen this issue if the fix is incomplete or if I misunderstood!
